### PR TITLE
feat: enable nodejs gc metrics

### LINKED ISSUE #138: add nodejs metrics
- https://github.com/siimon/prom-client?tab=readme-ov-file#default-metrics
- https://github.com/SimenB/node-prometheus-gc-stats

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

feat: enable nodejs gc metrics

## Description

Adds dependency on https://github.com/SimenB/node-prometheus-gc-stats and enables the collection of nodejs garbage collection metrics.

Fixes #138

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by SgtPooki — COMMENTED** [review]
self review

**Review by SgtPooki — COMMENTED** [review]
self review

**Review by wemeetagain — APPROVED** [review]

**Comment by wemeetagain** [comment]
Side note:
`gcStats` returns a timer id that can be cleared with `clearInterval`. Since the app assumes restart will be controlled from starting/stopping the process, we're not handling shutdown/restart of the node and metrics server, etc.
Just worth noting in case we decide to eg expose the bootstrapper with a js api.

**Comment by SgtPooki** [comment]
@achingbrain any thoughts here?

**Comment by achingbrain** [comment]
Does this plugin work?  The latest `prom-client` is 15, the `prometheus-gc-stats` README says it supports 10-14.

**Comment by SgtPooki** [comment]
> Does this plugin work? The latest `prom-client` is 15, the `prometheus-gc-stats` README says it supports 10-14.

Good call. I would defer to @wemeetagain for that question because he says lodestar are using it and it provides better metrics.. Also, there is the following line in the README:

> Note that version 12 and up of prom-client comes with GC metrics out of the box, so this module might not be needed. See https://github.com/siimon/prom-client/pull/361#discussion_r400430717.

**Pull request closed without merging**
